export const constants = {
  appVersion: process.env.REACT_APP_VERSION,
  apiURL: process.env.REACT_APP_API_ENDPOINT,
  homePage: 'https://ultranote.org',
  explorerURL: 'https://stats.ultranote.org/index.html#explorer',
  poolURL: 'https://stats.ultranote.org/index.html#pools',
  coingeckoAPI: 'https://api.coingecko.com/api/v3',
  discord: 'https://discordapp.com/invite/qHSNkH3',
  twitter: 'https://twitter.com/ultranotecoin',
  reddit: 'https://www.reddit.com/r/UltraNote/',
  telegram: 'https://t.me/ultranote_official',
  coinGecko: 'https://coingecko.com/en/coins/xuni',
  coinMarketCap: 'https://coinmarketcap.com/currencies/xuni',
  updateBlockchainHeightInterval: 30,  // seconds
  updateMarketPricesInterval: 120,  // seconds
  maxWallets: 3,
  coinDecimals: 6,
  defaultFee: 0.001000,
  messageFee: 0.0457000,
  selfDestructMessageFee: 0.001000,
  feePerChar: 0.000100,
  depositFee: 0.001000,
  investmentFee: 0.001000,
  withdrawalFee: 0.001000,
  idFee: 20,
  messageLimit: 260,
  qrCodePrefix: 'xuni',
};